# Dockerfile for fuzzing
# On amd64-based macOS, build with --platform=linux/x86_64

FROM ubuntu:20.04

WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y coreutils binutils curl git python3 g++ make gnupg openjdk-17-jdk-headless

# Install sbt
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add && \
    apt-get update && \
    apt-get install -y sbt

# Install Z3
RUN git clone https://github.com/Z3Prover/z3.git && \
    cd z3 && \
    python3 scripts/mk_make.py && \
    cd build && \
    make && \
    make install

# Install Portus
COPY org.alloytools.alloy.dist/target/org.alloytools.alloy.dist.jar /portus/portus.jar
# Building ourselves is failing due to SSL issues
#RUN git clone --recurse-submodules --single-branch --branch portus-fuzz https://github.com/watform/org.alloytools.alloy && \
#    cd org.alloytools.alloy && \
#    ./gradlew -Djavax.net.debug=all build && \
#    mkdir -p /portus && \
#    cp org.alloytools.alloy.dist/target/org.alloytools.alloy.dist.jar /portus/portus.jar

COPY --from=cifuzz/jazzer /app/* /jazzer/

WORKDIR /portus
ENTRYPOINT ["/jazzer/jazzer", "--cp=portus.jar", "--target_class=ca.uwaterloo.watform.portus.fuzz.ASTFuzzTarget", "--instrumentation_includes=ca.uwaterloo.watform.**", "--coverage_report=jazzer-coverage.txt", "--keep_going=10"]
