package ca.uwaterloo.watform.portus.fuzz;

import edu.mit.csail.sdg.alloy4.ConstList;
import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.Pair;
import edu.mit.csail.sdg.alloy4.SafeList;
import edu.mit.csail.sdg.ast.Assert;
import edu.mit.csail.sdg.ast.Browsable;
import edu.mit.csail.sdg.ast.Command;
import edu.mit.csail.sdg.ast.Expr;
import edu.mit.csail.sdg.ast.ExprConstant;
import edu.mit.csail.sdg.ast.Func;
import edu.mit.csail.sdg.ast.Module;
import edu.mit.csail.sdg.ast.Sig;

import java.util.ArrayList;
import java.util.List;

/**
 * A mock Module generated by ASTFuzzTarget.
 */
class GeneratedModule extends Browsable implements Module {

    private final ConstList<Sig> sigs;
    private final ConstList<Func> funcs;
    private final Command command;

    public GeneratedModule(List<Sig> sigs, List<Func> funcs, Command command) {
        this.sigs = ConstList.make(sigs);
        this.funcs = ConstList.make(funcs);
        this.command = command;
    }

    @Override
    public String getModelName() {
        return "FuzzGeneratedModule";
    }

    @Override
    public String path() {
        return "";
    }

    @Override
    public SafeList<? extends Module> getAllReachableModules() {
        // generated modules do not include other modules
        return new SafeList<>();
    }

    @Override
    public List<String> getAllReachableModulesFilenames() {
        // generated modules do not include other modules
        return new ArrayList<>();
    }

    @Override
    public ConstList<Sig> getAllReachableSigs() {
        ConstList.TempList<Sig> x = new ConstList.TempList<>();
        x.add(Sig.UNIV);
        x.add(Sig.SIGINT);
        x.add(Sig.SEQIDX);
        x.add(Sig.STRING);
        x.add(Sig.NONE);
        x.addAll(getAllReachableUserDefinedSigs());
        return x.makeConst();
    }

    @Override
    public ConstList<Sig> getAllReachableUserDefinedSigs() {
        // all sigs are defined in this module because we don't include other modules
        return sigs;
    }

    @Override
    public SafeList<Sig> getAllSigs() {
        return new SafeList<>(sigs);
    }

    @Override
    public SafeList<Func> getAllFunc() {
        return new SafeList<>(funcs);
    }

    @Override
    public ConstList<Assert> getAllAssertions() {
        // we do not define any assertions
        return ConstList.make();
    }

    @Override
    public SafeList<Pair<String, Expr>> getAllFacts() {
        // we do not define any facts separately from the command
        return new SafeList<>();
    }

    @Override
    public Expr getAllReachableFacts() {
        // we do not define any facts separately from the command or include any modules
        return ExprConstant.TRUE;
    }

    @Override
    public ConstList<Command> getAllCommands() {
        // we only define one command
        return ConstList.make(1, command);
    }

    @Override
    public void addGlobal(String name, Expr value) {
        // no-op: immutable
    }

    @Override
    public Expr parseOneExpressionFromString(String input) throws Err {
        throw new UnsupportedOperationException();
    }

    @Override
    public String explain() {
        return getModelName();
    }

    @Override
    public String getHTML() {
        return "";
    }

    @Override
    public List<? extends Browsable> getSubnodes() {
        return new ArrayList<>();
    }

}
