package ca.uwaterloo.watform.rapidDash;

import ca.uwaterloo.watform.ast.*;
import ca.uwaterloo.watform.parser.DashModule;
import com.google.gson.*;
import edu.mit.csail.sdg.alloy4.ErrorFatal;
import edu.mit.csail.sdg.ast.*;
import edu.mit.csail.sdg.translator.A4Solution;
import edu.mit.csail.sdg.translator.A4Tuple;

import java.io.*;
import java.util.*;
import java.util.stream.Collectors;

import static edu.mit.csail.sdg.alloy4.TableView.clean;

/**
 * Mutable; this class represents an Dash to Python translation module
 */

public class DashPythonTranslation {

    private DashModule dashModule;
    private A4Solution a4Solution;

    public List<Signature> signatures;
    public List<Relation> relations;
    public List<Event> allEnvEvents = new ArrayList<Event>();
    public State rootState = null;
    private Map<String, State> statesMap;

    private Map<String, String> variable2StateNameMap;  // maps variable names to state names or prefixes
    private Map<String, String> envVariable2VarNameMap; // maps env variable names to variable names

    public class Signature {
        public String name;
        public String multiplicity;     // TODO: could delete this
        public boolean isSubset;
        public boolean isSubsig;
        public boolean isAbstract;
        public boolean hasChildSubsig;
        public int scope;
        public boolean isOne;
        public boolean isLone;
        public List<String> parentNames;
        public String parentName;
        public List<String> objectNames;
        public List<String> subsigNames;
        public List<Signature> subsigs;

        public Signature(Sig sig, BufferedReader br, List<Signature> allSigs) {
            this.name = clean(sig.label);
            this.multiplicity = setMultiplicity(sig);       // TODO: could delete this
            this.isSubset = sig.isSubset != null;
            this.isSubsig = sig.isSubsig != null && ((Sig.PrimSig) sig).parent != Sig.UNIV;
            this.isAbstract = sig.isAbstract != null;
            this.isOne = sig.isOne != null;
            this.isLone = sig.isLone != null;

            // get parent names
            this.parentNames = (sig instanceof Sig.SubsetSig)? ((Sig.SubsetSig) sig).parents.stream().map(elem -> clean(elem.label)).collect(Collectors.toList()) : new ArrayList<>();
            this.parentName = (this.isSubsig)? clean(((Sig.PrimSig) sig).parent.label) : "";

            // list of subsigs
            this.subsigNames = new ArrayList<>();
            this.subsigs = new ArrayList<>();
            for(Signature otherSig : allSigs){
                if(otherSig.isSubsig && otherSig.parentName.equals(name)){
                    this.subsigs.add(otherSig);
                    this.subsigNames.add(otherSig.name);
                }
            }
            this.hasChildSubsig = !this.subsigNames.isEmpty();

            // Get values from solution generated by Alloy solver
//            if (a4Solution != null) {
//                this.objectNames = new ArrayList<>();
//                Sig ansSig = null;
//                for (Sig ansSigIter : a4Solution.getAllReachableSigs()) {
//                    if (ansSigIter.label.equals(sig.label)) {
//                        ansSig = ansSigIter;
//                        break;
//                    }
//                }
//                for (A4Tuple atom: a4Solution.eval(ansSig)) {
//                    this.objectNames.add(atom.toString());
//                }
//                this.objectNames.sort(Comparator.comparing(item -> item));
//                scope = this.objectNames.size();
//                return;
//            }

            // calculating objects (strings) and the final scope
            this.objectNames = new ArrayList<>();
            scope = getScopes(sig, this.objectNames.size(), br);
            if(isSubset) {
                // subset signatures will always take objects in its "parents"
                for (Signature otherSig : allSigs){
                    // TODO: might want to add some non-determinism here:
                    // since there are multiple possible sets of objects for a subset
                    // currently, we are only filling in the subset in a "fixed" way
                    if(parentNames.contains(otherSig.name)){
                        if(otherSig.objectNames.size() < (scope - this.objectNames.size())){
                            this.objectNames.addAll(otherSig.objectNames);
                        }else{
                            for(int i = this.objectNames.size(), j = 0; i < scope; i++, j++){
                                this.objectNames.add(otherSig.objectNames.get(j));
                            }
                            break;
                        }
                    }
                }
            }else{
                // regular signatures
                int sum_children_scope = 0;
                if(hasChildSubsig){
                    if(isLone) {
                        // assume the Alloy model is correct, then there will only be at most 1 One subsig and multiple Lone subsig
                        // if One sig exists, make this Lone sig in fact a One sig
                        for (Signature subsig : this.subsigs) {
                            if (subsig.isOne) {
                                this.objectNames.addAll(subsig.objectNames);
                                break;
                            }
                        }
                    }else{
                        if(isAbstract && !isLone && !isOne){
                            for(Signature subsig : this.subsigs){
                                this.objectNames.addAll(subsig.objectNames);
                            }
                        }else{
                            // TODO: might want to add some non-determinism:
                            // since there could be multiple subsigs for this signature
                            // currently, we are only filling in the signature in a "fixed" way
                            for(Signature subsig : this.subsigs){
                                sum_children_scope += subsig.scope;
                                if(subsig.objectNames.size() < (scope - this.objectNames.size())){
                                    this.objectNames.addAll(subsig.objectNames);
                                }else{
                                    for(int i = this.objectNames.size(), j = 0; i < scope; i++, j++){
                                        this.objectNames.add(subsig.objectNames.get(j));
                                    }
                                    break;
                                }
                            }
                        }
                    }
                }
                // add more elements if not reached the scope required
                if(!isAbstract){
                    for(int i = sum_children_scope; i < scope; i++) {
                        this.objectNames.add(name + "$" + i);
                    }
                }
            }
            this.objectNames.sort(Comparator.comparing(item -> item));
            scope = this.objectNames.size();
        }

        private String setMultiplicity(Sig sig) {
            if (sig.isLone != null)
                return "lone";
            if (sig.isOne != null)
                return "one";
            if (sig.isSome != null)
                return "some";
            return "set";
        }

        private int getScopes(Sig sig, int minimal_size, BufferedReader br) {
            if(isLone){return 0;}
            if(isOne){return 1;}
            if(sig.isSome != null){
                minimal_size = 1;
            }else if(minimal_size < 0){
                minimal_size = 0;
            }
            String input;

            // Only ask to use the config file if needed, and only once.
            if(!hasPromptedSigConfig){
                hasPromptedSigConfig = true;
                promptForUsingSignatureConfig();
            }

            // If the user wants to use the config file, try to get the scope from it.
            if(useSignatureConfig){
                int scope = getScopeFromConfig(sig, minimal_size);
                if (scope != -1) {
                    return scope;
                }
                needToUpdateConfigFile = true;
            }

            while(true){
                // TODO: check the value for subsig/subset
                // scope of the subsig/subset should not exceed the scope of its parent(s)
                // TODO: add default in the future (and or change this part to be reading from a config file)
                // System.out.printf("Choose a scope for %s, (type \"d\" for default):%n", clean(sig.label));

                if(useSignatureConfig){
                    System.out.printf("Cannot find \"$%s\" in the config file. ", clean(sig.label));
                }
                if(minimal_size != 0){
                    System.out.printf("Choose a scope for %s (at least %d, input < %d will be seen as %d):%n", clean(sig.label), minimal_size, minimal_size, minimal_size);
                }else{
                    System.out.printf("Choose a scope for %s (at least 0):%n", clean(sig.label));
                }
                try{
                    input = br.readLine();
                    int val = Integer.parseInt(input);
                    if(val < minimal_size){
                        val = minimal_size;
                    }
                    signatureScopeMap.put(sig.label, val);
                    return val;
                } catch(NumberFormatException ex){
                    System.out.print("Please input a valid number! ");
                } catch (Exception ex){
                    System.out.print(ex);
                }
            }
        }
        public String getName() { return name; }
        public String getMultiplicity() { return multiplicity; }    // TODO: could delete this
        public String getParentName() {
            if (this.parentName != null)
                return this.parentName;
            return "";
        }
        public String getParentsName() {return String.join(", ", this.parentNames);}
        public List<String> getParentNames() {return this.parentNames;}
        public List<String> getSubsigNames() {return this.subsigNames;}
        public String getObjectNames() {
            if(this.objectNames.isEmpty()){
                return "";
            }
            StringJoiner joiner = new StringJoiner("\", \"", "\"", "\"");
            for (CharSequence cs: this.objectNames) {
                joiner.add(cs);
            }
            return joiner.toString();
        }
        public void addObjects(List<String> objName) {
            this.objectNames.addAll(objName);
            this.scope += objName.size();
        }
        public void addObject(String objName) {
            this.objectNames.add(objName);
            this.scope++;
        }
        public boolean isSubsig() {return isSubsig;}
        public boolean isSubset() {return isSubset;}
        public boolean isAbstract() {return isAbstract;}
        public boolean hasChildSubsig() {return hasChildSubsig;}
    }


    private Boolean useSignatureConfig, hasPromptedSigConfig, needToUpdateConfigFile;
    private BufferedReader br;
    private JsonObject signatureJSONConfig;
    private HashMap<String, Integer> signatureScopeMap;

    private void initSignatures(List<Sig> signaturesSortedList){
        br = new BufferedReader(new InputStreamReader(System.in));
        useSignatureConfig = false;
        hasPromptedSigConfig = false;
        needToUpdateConfigFile = false;
        signatureJSONConfig = new JsonObject();
        signatureScopeMap = new HashMap<>();

        // get signatures
        this.signatures = new ArrayList<>();
        for(Sig sig : signaturesSortedList) {
            this.signatures.add(new Signature(sig, br, this.signatures));
        }

        // If didn't use config file, ask user if they wish to generate a config file for it.
        if (!useSignatureConfig || needToUpdateConfigFile){
            promptForStoringSignatureConfig();
        }

        try{
            br.close();
        }catch (IOException ex){
            System.out.print(ex);
        }
    }

    // Ask if user wants to use the config file when it exists.
    private void promptForUsingSignatureConfig(){
        File signatureConfigFile = new File(RapidDashOptions.inputDir);
        if(signatureConfigFile.exists() && !signatureConfigFile.isDirectory()) {
            useSignatureConfig = true;
            System.out.printf("Do you wish to use the existing signature config for scopes? (y/n)%n");
            try{
                String answer = br.readLine();
                useSignatureConfig = answer.equals("y") || answer.equals("");
            } catch (IOException ex){
                System.out.print(ex);
            }
        }

        // Read the config file.
        if(useSignatureConfig){
            try (Reader reader = new FileReader(signatureConfigFile)) {
                JsonElement jelement = new JsonParser().parse(reader);
                signatureJSONConfig = jelement.getAsJsonObject();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    // Save the config file.
    private void promptForStoringSignatureConfig(){
        File signatureConfigFile = new File(RapidDashOptions.inputDir);
        System.out.printf("Do you wish to %s the signature config for later use? (y/n)%n", needToUpdateConfigFile ? "update" : "save");
        try{
            String answer = br.readLine();
            if(!answer.equals("y") && !answer.equals("")){
                return;
            }
            // Save the config file.
            FileWriter fileWriter = new FileWriter(signatureConfigFile);
            Gson gson = new GsonBuilder()
                    .setPrettyPrinting()
                    .create();
            gson.toJson(signatureScopeMap, fileWriter);
            fileWriter.flush();
            fileWriter.close();
        } catch (IOException ex){
            System.out.print(ex);
        }
    }

    private int getScopeFromConfig(Sig sig, int minimal_size){
        if (signatureJSONConfig.get(sig.label) != null){
            int scope = signatureJSONConfig.get(sig.label).getAsInt();
            if (scope < minimal_size ){
                scope = minimal_size;
            }
            signatureScopeMap.put(sig.label, scope);
            return scope;
        }
        // Cannot find the scope in the config file.
        return -1;
    }

    public static class Relation {
        public String name;
        public String types;
        public List<List<String>> values = new ArrayList<>();;

        public Relation(String name, String types) {
            this.name = name;
            this.types = types;
        }

        public Relation(String name, String types, A4Solution a4Solution) {
            this.name = name;
            this.types = types;
            for (Sig s : a4Solution.getAllReachableSigs()) {
                for (Sig.Field f: s.getFields()){
                    if (f.label.equals(name)) {
                        for (A4Tuple atom: a4Solution.eval(f)) {
                            List<String> t = new ArrayList<>();
                            for (int i = 0; i < atom.arity(); i++) {
                                t.add(atom.atom(i));
                            }
                            this.values.add(t);
                        }
                        break;
                    }
                }
            }
        }

        public String getName() { return name; }
        public String getTypes() { return types; }

        public String getValues() {
            StringBuilder sb = new StringBuilder();
            sb.append("{");
            for (int i = 0; i < values.size(); i++) {
                if (i > 0)
                    sb.append(", ");
                sb.append("(");
                for (int j = 0; j < values.get(i).size(); j++) {
                    if (j > 0)
                        sb.append(", ");
                    sb.append("\"" + values.get(i).get(j) + "\"");
                }
                sb.append(")");
            }
            sb.append("}");
            return sb.toString();
        }

        @Override
        public boolean equals(Object object) {
            Relation otherRelation= (Relation) object; //downcasting from object to Person
            if (!this.name.equals(otherRelation.name)  || !this.types.equals(otherRelation.types)){
                return false;
            }
            return true;
        }
    }

    private String fieldDeclExprToString(Expr expr) {
        if (expr instanceof ExprVar) {
            return ((ExprVar) expr).label;
        } else if (expr instanceof ExprUnary) {
            return ((ExprVar) ((ExprUnary) expr).sub).label;
        } else if (expr instanceof ExprBinary) {
            if (!((ExprBinary) expr).op.isArrow) {
                // TODO: need to support union operator too.
                throw new ErrorFatal("Cannot handle operators other than arrow in field declarations");
            }
            return fieldDeclExprToString(((ExprBinary) expr).left) + ", " + fieldDeclExprToString(((ExprBinary) expr).right);
        }
        return "";
    }

    public class Event {
    	private String name;
    	private String modifiedName;
    	private boolean isEnvEvent;
    	private State parent;
    	
    	public Event(String name, String modifiedName, String type, State parent) {
    		this.name = name;
    		this.modifiedName = modifiedName;
    		this.isEnvEvent = type.equals("env event");
    		this.parent = parent;
    	}
    	
    	public String getModifiedName() {
    		return modifiedName;
    	}
    }

    /**
     * Constructs a new DashPythonTranslation object
     * @param dashModule - the DashModule we want to translate
     */
    public DashPythonTranslation(DashModule dashModule, A4Solution ans) {
        this.dashModule = dashModule;
        this.a4Solution = ans;

        // Sort the signatures based on dependencies (sort the list of signatures in topological order)
        List<Sig> signaturesOriginalList = new ArrayList<Sig>(dashModule.sigs.values());
        List<Sig> signaturesSortedList = topoSortSig(signaturesOriginalList);
        // subsigs <- sigs <- subsets

        // get signatures
        initSignatures(signaturesSortedList);

        // sort the signatures again, so it is in the same order as the input dash file
        Collections.sort(this.signatures, Comparator.comparing(item -> {
            for(int i = 0; i < signaturesOriginalList.size(); i++){
                if(item.name.equals(clean(signaturesOriginalList.get(i).label))){
                    return i;
                }
            }
            return -1;
        }));

        // get relations
        this.relations = new ArrayList<>();

        Set<Sig> keys = dashModule.old2fields.keySet();
        for (Sig key : keys) {
            // TODO: to filter out snapshot relations for now, might need to handle utility later
            if (dashModule.sigs.containsValue(key)){
                for (Decl decl : dashModule.old2fields.get(key)) {
                    String types = "[" + clean(key.label) + ", " + fieldDeclExprToString(decl.expr) + "]";
                    for (int i = 0; i < decl.names.size(); i++) {
                        if (a4Solution != null) {
                            relations.add(new Relation((decl.names.get(i)).label, types, a4Solution));
                        } else {
                            relations.add(new Relation((decl.names.get(i)).label, types));
                        }
                    }
                }
            }
        }

        // get state hierarchy
        this.statesMap = new HashMap<>();
        // initialize all states instances
        for(String stateName: dashModule.getConcurrentStateNames()){
            this.statesMap.put(stateName, new State(stateName, true));
        }
        for(String stateName: dashModule.getORStates().keySet()){
            this.statesMap.put(stateName, new State(stateName, false));
        }

        // process environmental variables
        this.variable2StateNameMap = new HashMap<>();
        this.envVariable2VarNameMap = new HashMap<>();

        addEnvVariableDeclarations();

        // process Concurrent states and add state variables
        for(DashConcState state: dashModule.getAllConcurrentStates().values()) {
            if(rootState == null) {
                rootState = this.statesMap.get(state.getFullyQualName());
            }
        	// add state variable declarations (decls)
            addVariableDeclarations(state);

        	// add state variable initializations and constraints (inits and init_constraints)
            if (a4Solution == null) {
                for(DashInit init: state.getInitialConds()) {
                    for(Expr expr: init.getAllExpressions()) {
                        // if the Dash init func is empty, there will be one expr that says "true"
                        if(expr.toString().equals("true")) {
                            continue;
                        }
                        DashExprToPython dashExprTranslator = new DashExprToPython<>(expr, variable2StateNameMap);
                        // TODO: this (and DashExprToPython) needs to be cleaned up
                        dashExprTranslator.isInit = true;
                        dashExprTranslator.reparseExpr();

                        // if the expression is a constraint on a variable's cardinality, add "assert"
                        // TODO: are other initialization constraint types possible? They need to be handled here
                        if(expr instanceof ExprBinary) {
                            ExprBinary binaryNode = (ExprBinary) expr;
                            if(binaryNode.left instanceof ExprUnary && ((ExprUnary)binaryNode.left).op == ExprUnary.Op.CARDINALITY) {
                                this.statesMap.get(state.getFullyQualName()).addInitConstraint("assert " + dashExprTranslator.toString());
                                continue;
                            }
                        }
                        this.statesMap.get(state.getFullyQualName()).addInit(dashExprTranslator.toString());
                    }
                }
            }


        	// add state events
        	for(DashEvent event: state.getEvents()) {
        		Event newEvent = new Event(event.getRawName(), event.getFullyQualName(), event.getType(), this.statesMap.get(state.getFullyQualName()));
        		this.statesMap.get(newEvent);
        		if(newEvent.isEnvEvent) {
        			allEnvEvents.add(newEvent);
        		}
        	}

            // add sub-states
        	for(DashConcState substate: state.getInnerConcStates()) {
        		this.statesMap.get(state.getFullyQualName()).addSubstate(this.statesMap.get(substate.getFullyQualName()));
        		this.statesMap.get(substate.getFullyQualName()).parent = statesMap.get(state.getFullyQualName());
        	}
        	for(DashState substate: state.getInnerORStates()) {
        		this.statesMap.get(state.getFullyQualName()).addSubstate(this.statesMap.get(substate.getFullyQualName()));
        		this.statesMap.get(substate.getFullyQualName()).parent = statesMap.get(state.getFullyQualName());
        		if(substate.isDefault() && this.statesMap.get(state.getFullyQualName()).defaultSubstate == null) {
        			this.statesMap.get(state.getFullyQualName()).defaultSubstate = this.statesMap.get(substate.getFullyQualName());
        		}
        	}
        }

        // process Or states
        for(DashState state: dashModule.getORStates().values()) {
            // add state variable declarations (decls)
            addVariableDeclarations(state);

            // add sub-states
            for(DashConcState substate: state.getInnerConcStates()) {
                this.statesMap.get(state.getFullyQualName()).addSubstate(this.statesMap.get(substate.getFullyQualName()));
                this.statesMap.get(substate.getFullyQualName()).parent = statesMap.get(state.getFullyQualName());
            }
        	for(DashState substate: state.getInnerORStates()) {
        		this.statesMap.get(state.getFullyQualName()).addSubstate(this.statesMap.get(substate.getFullyQualName()));
        		this.statesMap.get(substate.getFullyQualName()).parent = statesMap.get(state.getFullyQualName());
        	}
        }

        // generate transitions
        for(DashTrans dashTrans : dashModule.getTransitions().values()){
            Transition trans = new Transition(dashTrans);
            this.statesMap.get(trans.getStateName()).addTransition(trans);
            this.setTransStateActivenessChange(trans);
        }
    }

    private void setTransStateActivenessChange(Transition trans) {
        State s = this.statesMap.get(trans.getStateName());
        State d = this.statesMap.get(trans.getToStateName());
        State lca = rootState.LCA(s, d);

        // First get nodes to turn off
        HashSet<State> nodes_to_turn_off = new HashSet<State>();
        lca.getAllDescendentsExcludeMyself(nodes_to_turn_off);

        // Then get nodes to turn on
        HashSet<State> nodes_to_turn_on = new HashSet<State>();
        lca.initializePathToDescendent(d, nodes_to_turn_on);

        for (State n: nodes_to_turn_off) {
            // If something is turned off, then on, it is on, so we don't add it here
            if (!nodes_to_turn_on.contains(n)) {
                trans.nonActiveStatesAfterTrans.add(n);
            }
        }
        for (State n: nodes_to_turn_on) {
            trans.activeStatesAfterTrans.add(n);
        }
    }

    // return all states that aren't substates (to prevent them from appearing multiple times)
    public List<State> getRootStates() {
    	List<State> states = new ArrayList<>();
    	for(State state: statesMap.values()) {
    		if(state.parent == null) {
    			states.add(state);
    		}
    	}
    	return states;
    }

    public List<State> getAllStates() {
        List<State> states = new ArrayList<>();
        for(State state: statesMap.values()) {
            states.add(state);
        }
        return states;
    }

    // Declare state variables and add them into the map.
    private void addEnvVariableDeclarations() {

        // add the environmental variables
        for(Map.Entry<String,List<String>> envNames: dashModule.getEnvironmentalVarNames().entrySet()) {
            String stateName = envNames.getKey();
            for (String variableName : envNames.getValue()) {
                variable2StateNameMap.put(variableName, stateName);
                envVariable2VarNameMap.put(stateName + "_" + variableName, variableName);
                variable2StateNameMap.put(stateName + "_" + variableName, stateName);
            }
        }

        // add the environmental variable expressions
        for(Map.Entry<String, Expr> envExprs: dashModule.getEnvVarExpresssion().entrySet()) {
            String envName = envExprs.getKey();
            String variableName = envVariable2VarNameMap.get(envName);
            String stateName = variable2StateNameMap.get(envName);

            DashExprToPython dashExprTranslator = new DashExprToPython<>(envExprs.getValue(), variable2StateNameMap, variableName, this.relations);
            statesMap.get(stateName).addDecl(envName + " = " + dashExprTranslator);
        }
    }

    // Declare state variables and add them into the map.
    private void addVariableDeclarations(DashSuperState state) {
        Sig snapshot = null;
        if (a4Solution != null) {
            // Find Snapshot signature from a4Solution
            for (Sig sigIter : a4Solution.getAllReachableSigs()) {
                if (clean(sigIter.label).equals("Snapshot")) {
                    snapshot = sigIter;
                    break;
                }
            }
        }
        for(Decl decl: state.getVariables()) {

            String stateName = state.getFullyQualName();
            String variableName = decl.get().toString();
            variable2StateNameMap.put(variableName, stateName);

            if (a4Solution != null) {
                // Find Snapshot signature from a4Solution
                boolean found = false;
                for (Sig.Field f : snapshot.getFields()) {
                    if (f.label.equals(stateName + "_" + variableName)) {
                        String className = "Signature";
                        String multiplicityOrTypes = "3";
                        String values = "{}";
                        for (Type.ProductType type : f.type()) {
                            if (type.arity() == 2) {
                                // Signature
                                className = clean(type.get(1).label);
                                List<String> atoms = new ArrayList<String>();
                                for (A4Tuple atom: a4Solution.eval(f,0)) {
                                    if (atom.atom(0).equals("Snapshot$0")) {
                                        atoms.add("\"" + atom.atom(1) + "\"");
                                    }
                                }
                                values = "{" + String.join(", ", atoms) + "}";
                            } else {
                                // Relation
                                className = "Relation";
                                List<String> typeStrings = new ArrayList<String>();
                                for (int i = 1; i < type.arity(); i++) {
                                    typeStrings.add(clean(type.get(i).label));
                                }
                                multiplicityOrTypes = "[" + String.join(", ", typeStrings) + "]";
                                List<String> atoms = new ArrayList<String>();
                                for (A4Tuple atom : a4Solution.eval(f, 0)) {
                                    if (atom.atom(0).equals("Snapshot$0")) {
                                        List<String> tuple = new ArrayList<String>();
                                        for (int i = 1; i < atom.arity(); i++) {
                                            tuple.add("\"" + atom.atom(i) + "\"");
                                        }
                                        atoms.add("(" + String.join(", ", tuple) + ")");
                                    }
                                }
                                values = "{" + String.join(", ", atoms) + "}";
                            }
                        }
                        statesMap.get(stateName).addDecl(stateName + "_" + variableName + " = " + className + "('" + variableName + "', " + multiplicityOrTypes + ", " + values + ")");
                        found = true;
                        break;
                    }
                }
                if (!found) {
                    throw new ErrorFatal("Cannot find state variable " + stateName + "_" + variableName + " in the solution");
                }
            } else {
                DashExprToPython dashExprTranslator = new DashExprToPython<>(decl.expr, variable2StateNameMap, variableName, this.relations);
                dashExprTranslator.isDecl = true;
                statesMap.get(stateName).addDecl(stateName + "_" + variableName + " = " + dashExprTranslator);
            }
        }
    }

    private void dfs(List<Sig> outputList, Set<String> covered, Set<Sig> subsets, Sig sig){
        if(covered.contains(clean(sig.label))){
            return;
        }
        if(sig instanceof Sig.PrimSig && ((Sig.PrimSig) sig).parent != null) {
            dfs(outputList, covered, subsets, ((Sig.PrimSig) sig).parent);
            outputList.add(sig);
        }else if(sig instanceof Sig.SubsetSig && ((Sig.SubsetSig) sig).parents != null){
            subsets.add(sig);
        }
        covered.add(clean(sig.label));
    }
    private List<Sig> topoSortSig(List<Sig> list){
        Deque<Sig> signaturesOriginalQueue = new ArrayDeque<Sig>(list);
        List<Sig> signaturesSortedList = new ArrayList<Sig>();
        Set<String> covered = new HashSet<String>();
        Set<Sig> subsets = new HashSet<Sig>();
        while (signaturesOriginalQueue.size() != 0) {
            Sig sig = signaturesOriginalQueue.pop();
            dfs(signaturesSortedList, covered, subsets, sig);
        }
        Collections.reverse(signaturesSortedList);
        signaturesSortedList.addAll(subsets);
        return signaturesSortedList;
    }

    public class State{
        private String stateName;                       // state name
        private List<Transition>  transitions;   // store the translated code for transitions
        private List<State> substates;
        private List<String> decls;
        private List<String> inits;
        private List<String> init_constraints;

        private boolean isConc;
        private List<Event> events;
        public State parent = null;
        public State defaultSubstate = null;
        public State(String stateName, boolean isConc){
            this.stateName = stateName;
            this.transitions = new ArrayList<>();
            this.substates = new ArrayList<State>();
            this.decls = new ArrayList<String>();
            this.inits = new ArrayList<String>();
            this.init_constraints = new ArrayList<String>();
            this.isConc = isConc;
        }
        public void addTransition(Transition transition){
            this.transitions.add(transition);
        }
        public String getName(){return stateName;}
        public String getPythonVariableName() {return "ref_" + stateName.toLowerCase();}
        public List<Transition> getTransitions() {return transitions.stream().collect(Collectors.toList());}
        public List<State> getSubstates() { return substates.stream().collect(Collectors.toList()); }
        public List<String> getDecls() { return decls.stream().collect(Collectors.toList()); }
        public List<String> getInits() { return inits.stream().collect(Collectors.toList()); }
        public List<String> getInitConstraints() { return init_constraints.stream().collect(Collectors.toList()); }
        public List<Event> getEvents() { return events.stream().collect(Collectors.toList()); }

        public boolean getIsConc() {return isConc;}

        public boolean isRootState() { return parent == null; }

        public void addSubstate(State s) { substates.add(s); }
        public void addDecl(String s) { decls.add(s); }
        public void addInit(String s) { inits.add(s); }
        public void addInitConstraint(String s) { init_constraints.add(s); }
        public void addEvent(Event e) { events.add(e); }
        public State getDefaultSubstate() {
        	return defaultSubstate != null ? defaultSubstate : substates.get(0);
        }

        /**
         * Get the lowest common ancestor of two nodes
         * @param n1 first node
         * @param n2 second node
         * @return the lowest common ancestor
         */
        public State LCA(State n1, State n2) {
            if (n1 == n2) return n1;
            if (this == n1 || this == n2) return this;
            int count = 0;
            State temp = null;
            for(State child : getSubstates()) {
                State result = child.LCA(n1, n2);
                if(result != null) {
                    count++;
                    temp = result;
                }
            }

            if(count == 2) {
                return this;
            }

            return temp;
        }

        public boolean pathToDescendentInclusive(State descendent, Stack<State> path) {
            // push the node's value in 'arr'
            path.add(this);

            // if it is the required node
            // return true
            if (this == descendent)
                return true;

            for (State child : getSubstates()) {
                if (child.pathToDescendentInclusive(descendent, path)) {
                    return true;
                }
            }

            path.pop();
            return false;
        }
        
        public void getAllDescendentsExcludeMyself(HashSet<State> nodes) {
            for (State child : getSubstates()) {
                nodes.add(child);
                child.getAllDescendentsExcludeMyself(nodes);
            }
        }

        public void initializePathToDescendent(State descendent, HashSet<State> nodes) {
            if (descendent == this) {
                nodes.add(descendent);
                return;
            }
            Stack<State> path = new Stack<State>();
            pathToDescendentInclusive(descendent, path);

            assert descendent == path.pop();

            descendent.getDefaultInitializationSet(nodes);

            while(path.size() > 1) {
                State node = path.pop();
                nodes.add(node);
                if (node.isConc) {
                    // need to initialize conc siblings as well
                    // guaranteed to have a parent since it is not root
                    for (State sibling : node.parent.getSubstates()) {
                        sibling.getDefaultInitializationSet(nodes);
                    }
                }
            }

            assert this == path.pop();
        }

        /**
         * Default initialize current node, nodes are all the nodes that will become active
         * @param nodes
         */
        public void getDefaultInitializationSet(HashSet<State> nodes) {
            nodes.add(this);
            if (getSubstates().isEmpty()) {
                return;
            }

            boolean is_children_conc = getSubstates().get(0).isConc;
            if (is_children_conc) {
                for (State child : getSubstates()) {
                    child.getDefaultInitializationSet(nodes);
                }
            } else if(getDefaultSubstate() != null) {
                getDefaultSubstate().getDefaultInitializationSet(nodes);
            }
        }
    }

    public class Transition{
        private String stateName;                       // state name

        private String fromStateName = "";
        private String toStateName = "";
        private String transName = "";                       // transition name
        private List<String> actions = new ArrayList<>();    // the logic for this transition to be executed
        private List<String> guardConditions = new ArrayList<>();   // the guard conditions of this transition
        private String eventCondition = "";
        private String triggerEvent = "";
        private String transTemplate = "";

        public HashSet<State> nonActiveStatesAfterTrans = new HashSet<State>();
        public HashSet<State> activeStatesAfterTrans = new HashSet<State>();

        public Transition(DashTrans dashTrans){
            // set default transition information
            this.transName = dashTrans.getRawName();
            if (dashTrans.getParent() instanceof DashConcState) {
                this.stateName = ((DashConcState)dashTrans.getParent()).getFullyQualName();
            } else {
                this.stateName = ((DashState)dashTrans.getParent()).getFullyQualName();
            }

            // check keywords
            if(dashTrans.getOrigin() != null){    // determines which state this transition belongs to
                this.fromStateName = dashTrans.getOrigin().getAllOrigins().get(0);
            }
            if(dashTrans.getTriggerEvent() != null){      // determines the trigger event
                this.eventCondition = dashTrans.getTriggerEvent().getRawName();
            }
            if(dashTrans.getCondition() != null){    // determines the guard_condition (if statement)
                DashExprToPython dashExprTranslator = new DashExprToPython<>(dashTrans.getCondition(), variable2StateNameMap);

                // set condition
                this.guardConditions = dashExprTranslator.toList();
            }
            if(dashTrans.getAction() != null){      // determines the action
                DashExprToPython dashExprTranslator = new DashExprToPython<>(dashTrans.getAction(), variable2StateNameMap);

                // set actions
                this.actions = dashExprTranslator.toList();
            }
            if(dashTrans.getDestination() != null){    // determine the next state
                this.toStateName = dashTrans.getDestination().getAllDestinations().get(0).replace("/", "_");
            }
            if(dashTrans.getEventsTriggered() != null){    // determines the event to send
                this.triggerEvent = dashTrans.getEventsTriggered().getRawName();
            }
            if(dashTrans.getTransTemplate() != null){   // TODO: don't know what this does
                this.transTemplate = "pass\t# <placeholder for Trans Template>";
            }
        }
        public String getTransName(){return transName;}
        public String getStateName(){return stateName;}
        public List<String> getGuardConditions(){return guardConditions;}
        public List<String> getActions(){return actions;}
        public String getEventCondition() {return eventCondition;}
        public String getFromStateName() {return fromStateName;}
        public String getToStateName() {return toStateName;}
        public String getTransTemplate() {return transTemplate;}
        public String getTriggerEvent() {return triggerEvent;}
        public HashSet<State> getNonActiveStatesAfterTrans() {return nonActiveStatesAfterTrans;}
        public HashSet<State> getActiveStatesAfterTrans() {return activeStatesAfterTrans;}
        private String getStatesAfterTransPythonStr(HashSet<State> state) {
            StringBuilder b = new StringBuilder();
            b.append("[");
            b.append(state.stream().map(s -> s.getPythonVariableName()).collect(Collectors.joining(",")));
            b.append("]");
            return b.toString();
        }
        public String getNonActiveStatesAfterTransPythonStr() {
            return getStatesAfterTransPythonStr(nonActiveStatesAfterTrans);
        }

        public String getActiveStatesAfterTransPythonStr() {
            return getStatesAfterTransPythonStr(activeStatesAfterTrans);
        }

    }
}
