package ca.uwaterloo.watform.portus;

import java.util.Optional;

/**
 * A hook into the SATFactory system to enable outputting Fortress MSFOL debug output.
 */
public class FortressMSFOLTransformer extends PortusSATFactory {

    public static final String ID = "fortress/raw-msfol";

    @Override
    public String id() {
        return ID;
    }

    @Override
    public String name() {
        return "Output Fortress MSFOL to file";
    }

    @Override
    public Optional<String> getDescription() {
        return Optional.of("This dumps the Fortress theory generated by Portus to a file.");
    }

    @Override
    public String type() {
        return "transformer";
    }

    @Override
    public boolean isTransformer() {
        return true;
    }

}
