package ca.uwaterloo.watform.portus;

import edu.mit.csail.sdg.alloy4.ErrorFatal;
import fortress.msfol.Sort;
import fortress.msfol.Term;

import java.util.Collections;
import java.util.List;
import java.util.function.Function;

/**
 * Represents a scalar or a function of scalars, including its guard.
 * True scalars are represented by nilary functions of scalars.
 *
 * Definition: An Alloy expression e of arity n+1 and definite sorts (S1, ..., Sn, T) is a scalar function of arity n if
 * there exists an MSFOL function f : S1 x ... x Sn -> T and an MSFOL predicate guard : S1 x ... x Sn -> Bool such that
 * for any MSFOL atoms x1: S1, ..., xn: Sn, y: T,
 *    [[(x1, ..., xn, y) \in e]] is equivalent to f(x1, ..., xn) = y.
 * A scalar is a scalar function of arity 0 (i.e., a regular scalar).
 * Note that we have chosen the last index in e to be the function output arbitrarily!
 * This ensures that we are compatible with Alloy join (see {@link #compose(Scalar, Scalar)}.
 * Notably, this precludes representing an Alloy function f : A->one B->C as a function f(a,c) -> b.
 * TODO: Can we generalize to output from any index if possible?
 */
final class Scalar {

    // The sorts of the arguments expected by scalarGenerator and guardGenerator.
    private final List<Sort> argSorts;

    // The sort of the term generated by scalarGenerator. Must always be the same sort.
    private final Sort resultSort;

    private final Function<TermTuple, Term> scalarGenerator;
    private final Function<TermTuple, Term> guardGenerator;

    public Scalar(List<Sort> argSorts, Sort resultSort, Function<TermTuple, Term> scalarGenerator,
                  Function<TermTuple, Term> guardGenerator) {
        this.argSorts = argSorts;
        this.resultSort = resultSort;
        this.scalarGenerator = scalarGenerator;
        this.guardGenerator = guardGenerator;
    }

    /** Create a nilary scalar. */
    public Scalar(Sort resultSort, Term scalar, Term guard) {
        this(Collections.emptyList(), resultSort, tuple -> scalar, tuple -> guard);
    }

    /** Create a nilary scalar. */
    public Scalar(AnnotatedTerm scalar, Term guard) {
        this(scalar.getSort(), scalar.getTerm(), guard);
    }

    public int getArity() {
        return argSorts.size();
    }

    public boolean isNilary() {
        return getArity() == 0;
    }

    public List<Sort> getArgSorts() {
        return argSorts;
    }

    public Sort getResultSort() {
        return resultSort;
    }

    /** Return whether this and other have the same arity and arg and result sorts. */
    public boolean hasSameSignature(Scalar other) {
        return getArgSorts().equals(other.getArgSorts()) && getResultSort().equals(other.getResultSort());
    }

    public Term getScalar(TermTuple tuple) {
        if (!tuple.getSorts().equals(getArgSorts())) {
            throw new ErrorFatal("Internal Portus error: getScalar passed tuple of incorrect sorts!");
        }
        return scalarGenerator.apply(tuple);
    }

    public Term getNilaryScalar() {
        return getScalar(new TermTuple());
    }

    public AnnotatedTerm getAnnotatedScalar(TermTuple args) {
        return new AnnotatedTerm(getScalar(args), getResultSort());
    }

    public AnnotatedTerm getNilaryAnnotatedScalar() {
        return getAnnotatedScalar(new TermTuple());
    }

    public Term getGuard(TermTuple tuple) {
        if (!tuple.getSorts().equals(getArgSorts())) {
            throw new ErrorFatal("Internal Portus error: getGuard passed tuple of incorrect sorts!");
        }
        return guardGenerator.apply(tuple);
    }

    public Term getNilaryGuard() {
        return getGuard(new TermTuple());
    }

    /**
     * Compose two scalars together. Given scalars f and g, compute g o f.
     * Specifically, given f : x1, ..., xn |-> f(x1, ..., xn) and g : y1, ..., ym |-> g(y1, ..., ym), compute
     *      g o f : x1, ..., xn, y2, ..., ym |-> g(f(x1, ..., xn), y2, ..., ym).
     * If g is nilary, throw an error.
     * Other combinations are theoretically possible, but this corresponds to the Alloy join f.g.
     */
    public static Scalar compose(Scalar f, Scalar g) {
        if (g.isNilary()) {
            throw new ErrorFatal("Cannot compose scalars (g o f) where g is nilary!");
        }

        int arity = f.getArity() + g.getArity() - 1;
        List<Sort> argSorts = SetOps.concatenate(f.getArgSorts(), g.getArgSorts().subList(1, g.getArity()));
        Function<TermTuple, Term> scalarGenerator = tuple -> {
            // g(f(x1, ..., xn), y2, ..., ym)
            TermTuple fArgs = tuple.slice(0, f.getArity());
            AnnotatedTerm fResult = f.getAnnotatedScalar(fArgs);
            TermTuple gArgs = new TermTuple(fResult).concat(tuple.slice(f.getArity(), arity));
            return g.getScalar(gArgs);
        };
        Function<TermTuple, Term> guardGenerator = tuple -> {
            // guard_f(x1, ..., xn) && guard_g(f(x1, ..., xn), y2, ..., ym)
            TermTuple fArgs = tuple.slice(0, f.getArity());
            AnnotatedTerm fResult = f.getAnnotatedScalar(fArgs);
            TermTuple gArgs = new TermTuple(fResult).concat(tuple.slice(f.getArity(), arity));
            return Term.mkAnd(f.getGuard(fArgs), g.getGuard(gArgs));
        };
        return new Scalar(argSorts, g.getResultSort(), scalarGenerator, guardGenerator);
    }

}
