package ca.uwaterloo.watform.portus;

import edu.mit.csail.sdg.alloy4.ErrorFatal;
import fortress.msfol.AnnotatedVar;
import fortress.msfol.Sort;
import fortress.msfol.Term;

import java.util.Collections;
import java.util.List;
import java.util.function.BiFunction;
import java.util.function.Function;

/**
 * Represents a scalar or a function of scalars, including its guard.
 * True scalars are represented by nilary functions of scalars.
 *
 * Definition: An Alloy expression e of arity n+1 and definite sorts (S1, ..., Sn, T) is a scalar function of arity n if
 * there exists an MSFOL function f : S1 x ... x Sn -> T and an MSFOL predicate guard : S1 x ... x Sn -> Bool such that
 * for any MSFOL atoms x1: S1, ..., xn: Sn, y: T,
 *    [[(x1, ..., xn, y) \in e]] is equivalent to f(x1, ..., xn) = y.
 * A scalar is a scalar function of arity 0 (i.e., a regular scalar).
 * Note that we have chosen the last index in e to be the function output arbitrarily!
 * This ensures that we are compatible with Alloy join (see {@link #compose(Scalar, Scalar, VarMappingContext)}.
 * Notably, this precludes representing an Alloy function f : A->one B->C as a function f(a,c) -> b.
 * TODO: Can we generalize to output from any index if possible?
 */
// Idea: maybe it'll speed it up if sometimes we make functions for scalar/guard
final class Scalar {

    /** A function that can generate a term. The passed context should be used for any translations needed. */
    @FunctionalInterface
    public interface TermGenerator extends BiFunction<TermTuple, TranslationContext, Term> {}

    // The sorts of the arguments expected by scalarGenerator and guardGenerator.
    private final List<Sort> argSorts;

    // The sort of the term generated by scalarGenerator. Must always be the same sort.
    private final Sort resultSort;

    private final TermGenerator scalarGenerator;
    private final TermGenerator guardGenerator;

    // The saved context at the point that the scalar appears.
    private final VarMappingContext savedContext;

    /**
     * Create a scalar with the given scalar and guard generators.
     * The context term passed to the scalar and guard generators is the context that should be used for any
     * translations needed to generate the scalar or guard.
     */
    public Scalar(List<Sort> argSorts, Sort resultSort, TermGenerator scalarGenerator, TermGenerator guardGenerator,
                  VarMappingContext savedContext) {
        this.argSorts = argSorts;
        this.resultSort = resultSort;
        this.scalarGenerator = scalarGenerator;
        this.guardGenerator = guardGenerator;
        this.savedContext = new VarMappingContext(savedContext); // copy and freeze it
    }

    /**
     * Create a scalar with the given scalar and guard generators.
     * The context term passed to the scalar and guard generators is the context that should be used for any
     * translations needed to generate the scalar or guard.
     */
    public Scalar(List<Sort> argSorts, Sort resultSort, TermGenerator scalarGenerator, TermGenerator guardGenerator,
                  TranslationContext savedContext) {
        this(argSorts, resultSort, scalarGenerator, guardGenerator, savedContext.getVarMappingContext());
    }

    /**
     * Create a scalar. This constructor should be used when the context parameter to the scalar and guard generators
     * is not needed. Note that then the scalar and guard should not rely on any external context!
     */
    public Scalar(List<Sort> argSorts, Sort resultSort, Function<TermTuple, Term> scalarGenerator,
                  Function<TermTuple, Term> guardGenerator, VarMappingContext savedContext) {
        this(argSorts, resultSort, (tuple, context) -> scalarGenerator.apply(tuple),
                (tuple, context) -> guardGenerator.apply(tuple), savedContext);
    }

    /**
     * Create a scalar. This constructor should be used when the context parameter to the scalar and guard generators
     * is not needed. Note that then the scalar and guard should not rely on any external context!
     */
    public Scalar(List<Sort> argSorts, Sort resultSort, Function<TermTuple, Term> scalarGenerator,
                  Function<TermTuple, Term> guardGenerator, TranslationContext savedContext) {
        this(argSorts, resultSort, scalarGenerator, guardGenerator, savedContext.getVarMappingContext());
    }

    /** Create a nilary scalar. */
    public Scalar(Sort resultSort, Term scalar, Term guard, VarMappingContext savedContext) {
        this(Collections.emptyList(), resultSort, tuple -> scalar, tuple -> guard, savedContext);
    }

    /** Create a nilary scalar. */
    public Scalar(Sort resultSort, Term scalar, Term guard, TranslationContext savedContext) {
        this(resultSort, scalar, guard, savedContext.getVarMappingContext());
    }

    /** Create a nilary scalar. */
    public Scalar(AnnotatedTerm scalar, Term guard, VarMappingContext savedContext) {
        this(scalar.getSort(), scalar.getTerm(), guard, savedContext);
    }

    /** Create a nilary scalar. */
    public Scalar(AnnotatedTerm scalar, Term guard, TranslationContext savedContext) {
        this(scalar, guard, savedContext.getVarMappingContext());
    }

    public int getArity() {
        return argSorts.size();
    }

    public boolean isNilary() {
        return getArity() == 0;
    }

    public List<Sort> getArgSorts() {
        return argSorts;
    }

    public Sort getResultSort() {
        return resultSort;
    }

    /** Return whether this and other have the same arity and arg and result sorts. */
    public boolean hasSameSignature(Scalar other) {
        return getArgSorts().equals(other.getArgSorts()) && getResultSort().equals(other.getResultSort());
    }

    public Term getScalar(TermTuple tuple, TranslationContext context) {
        if (!tuple.getSorts().equals(getArgSorts())) {
            throw new ErrorFatal("Internal Portus error: getScalar passed tuple of incorrect sorts!");
        }
        return callTermGenerator(scalarGenerator, tuple, context);
    }

    public TermGenerator getScalarGenerator() {
        return scalarGenerator;
    }

    public Term getNilaryScalar(TranslationContext context) {
        return getScalar(new TermTuple(), context);
    }

    public AnnotatedTerm getAnnotatedScalar(TermTuple args, TranslationContext context) {
        return new AnnotatedTerm(getScalar(args, context), getResultSort());
    }

    public AnnotatedTerm getNilaryAnnotatedScalar(TranslationContext context) {
        return getAnnotatedScalar(new TermTuple(), context);
    }

    public Term getGuard(TermTuple tuple, TranslationContext context) {
        if (!tuple.getSorts().equals(getArgSorts())) {
            throw new ErrorFatal("Internal Portus error: getGuard passed tuple of incorrect sorts!");
        }
        return callTermGenerator(guardGenerator, tuple, context);
    }

    public Term getNilaryGuard(TranslationContext context) {
        return getGuard(new TermTuple(), context);
    }

    private Term callTermGenerator(TermGenerator generator, TermTuple tuple, TranslationContext newContext) {
        // Use the new context (for mutable additions to the theory, etc) with the old var mapping context PLUS the
        // mappings for all the free variables in the tuple, according to the new context.
        List<AnnotatedVar> tupleFreeVars = tuple.getAllFreeVars(newContext);
        try {
            savedContext.addFortressVars(tupleFreeVars);
            return newContext.withVarMappingContext(savedContext, context -> generator.apply(tuple, context));
        } finally {
            savedContext.removeFortressVars(tupleFreeVars);
        }
    }

    /**
     * Compose two scalars together. Given scalars f and g, compute g o f.
     * Specifically, given f : x1, ..., xn |-> f(x1, ..., xn) and g : y1, ..., ym |-> g(y1, ..., ym), compute
     *      g o f : x1, ..., xn, y2, ..., ym |-> g(f(x1, ..., xn), y2, ..., ym).
     * If g is nilary, throw an error.
     * Other combinations are theoretically possible, but this corresponds to the Alloy join f.g.
     */
    public static Scalar compose(Scalar f, Scalar g, VarMappingContext newContext) {
        if (g.isNilary()) {
            throw new ErrorFatal("Cannot compose scalars (g o f) where g is nilary!");
        }

        int arity = f.getArity() + g.getArity() - 1;
        List<Sort> argSorts = SetOps.concatenate(f.getArgSorts(), g.getArgSorts().subList(1, g.getArity()));
        TermGenerator scalarGenerator = (tuple, context) -> {
            // g(f(x1, ..., xn), y2, ..., ym)
            TermTuple fArgs = tuple.slice(0, f.getArity());
            AnnotatedTerm fResult = f.getAnnotatedScalar(fArgs, context);
            TermTuple gArgs = new TermTuple(fResult).concat(tuple.slice(f.getArity(), arity));
            return g.getScalar(gArgs, context);
        };
        TermGenerator guardGenerator = (tuple, context) -> {
            // guard_f(x1, ..., xn) && guard_g(f(x1, ..., xn), y2, ..., ym)
            TermTuple fArgs = tuple.slice(0, f.getArity());
            AnnotatedTerm fResult = f.getAnnotatedScalar(fArgs, context);
            TermTuple gArgs = new TermTuple(fResult).concat(tuple.slice(f.getArity(), arity));
            return Term.mkAnd(f.getGuard(fArgs, context), g.getGuard(gArgs, context));
        };
        return new Scalar(argSorts, g.getResultSort(), scalarGenerator, guardGenerator, newContext);
    }

    /**
     * Compute f ++ g. If f and g have compatible sorts and arity n then:
     *    (f ++ g)(x) = guard_g(x) ? g(x) : f(x)
     *    guard_(f ++ g)(x) = guard_g(x) || (!guard_g(x) && guard_f(x)) === guard_g(x) || guard_f(x)
     * This corresponds to Alloy override (++).
     */
    public static Scalar override(Scalar f, Scalar g, VarMappingContext newContext) {
        if (!f.hasSameSignature(g)) {
            throw new ErrorFatal("Cannot compute override (++) of incompatible scalars!");
        }

        TermGenerator scalarGenerator = (tuple, context) -> Term.mkIfThenElse(
                g.getGuard(tuple, context), g.getScalar(tuple, context), f.getScalar(tuple, context));
        TermGenerator guardGenerator = (tuple, context) -> Term.mkOr(
                g.getGuard(tuple, context), f.getGuard(tuple, context));
        return new Scalar(f.getArgSorts(), f.getResultSort(), scalarGenerator, guardGenerator, newContext);
    }

    @Override
    public String toString() {
        return "(" + argSorts.stream().map(Sort::toString).reduce((str, sort) -> str + ", " + sort).orElse("")
                + ") -> " + resultSort;
    }

}
