package ca.uwaterloo.watform.portus;

import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.ErrorFatal;
import edu.mit.csail.sdg.alloy4.Pair;
import edu.mit.csail.sdg.ast.Assert;
import edu.mit.csail.sdg.ast.Decl;
import edu.mit.csail.sdg.ast.Expr;
import edu.mit.csail.sdg.ast.ExprBinary;
import edu.mit.csail.sdg.ast.ExprCall;
import edu.mit.csail.sdg.ast.ExprConstant;
import edu.mit.csail.sdg.ast.ExprHasName;
import edu.mit.csail.sdg.ast.ExprITE;
import edu.mit.csail.sdg.ast.ExprLet;
import edu.mit.csail.sdg.ast.ExprList;
import edu.mit.csail.sdg.ast.ExprQt;
import edu.mit.csail.sdg.ast.ExprUnary;
import edu.mit.csail.sdg.ast.ExprVar;
import edu.mit.csail.sdg.ast.Func;
import edu.mit.csail.sdg.ast.Sig;
import edu.mit.csail.sdg.ast.Type;
import edu.mit.csail.sdg.parser.Macro;
import edu.mit.csail.sdg.translator.ScopeComputer;
import fortress.modelfind.ModelFinder;
import fortress.msfol.AnnotatedVar;
import fortress.msfol.Sort;
import fortress.msfol.Theory;
import fortress.problemstate.Scope;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.BiFunction;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.StreamSupport;

/**
 * An abstraction responsible for assigning sigs to sorts. Should be immutable.
 */
abstract class SortPolicy {

    protected final List<Sig> allSigs;

    public SortPolicy(Iterable<Sig> allSigs) {
        this.allSigs = PortusUtil.iterableToList(allSigs);
    }

    /**
     * Get the sort assigned to a given signature. Should have no side effects.
     * May return null for sigs that cannot be assigned a sort (e.g. univ, none) since they encompass all sorts.
     */
    public abstract Sort getSort(Sig sig);

    /**
     * Get the scope of the given sort. Assert that it was one generated by the sort policy.
     * Note that as a special case, the scope of Int is the bitwidth, and not the number of integers (2^bitwidth).
     */
    public abstract int getSortScope(Sort sort);

    /** Return a theory with the sorts assigned by the policy added. */
    public abstract Theory addSortsToTheory(Theory theory);

    /**
     * Add all the scopes of the sorts to the model finder.
     * {@code unchangingSorts} is the list of sorts which should be marked as 'unchanging': their scope cannot be
     * changed in the output (without messing up the semantics of the problem).
     */
    public void configureModelFinderScopes(ModelFinder modelFinder, Set<Sort> unchangingSorts) {
        for (Map.Entry<Sort, Scope> sortAndScope : getSortToScopeMap(unchangingSorts).entrySet()) {
            modelFinder.setScope(sortAndScope.getKey(), sortAndScope.getValue());
        }
    }

    /**
     * Get a map of sorts assigned by the policy to their Fortress scopes.
     * This method is for configuring model finders and dumping. Use getSortScope() for most use-cases.
     */
    public abstract Map<Sort, Scope> getSortToScopeMap(Set<Sort> unchangingSorts);

    /** Get the inclusive range of domain element indices in the sort spanned by this sig. */
    public Pair<Integer, Integer> getDomainElementRange(Sig sig, ScopeComputer scoper) {
        if (!(sig instanceof Sig.PrimSig)) {
            // TODO: can we support subset sigs?
            return null;
        }
        if (sig == Sig.SIGINT) {
            // domain elements of Int are special, so we don't support them
            return null;
        }
        if (!scoper.isExact(sig)) {
            // we only support exact scopes - a warning for the ordering module is printed in that optimization
            return null;
        }

        Sig.PrimSig primSig = (Sig.PrimSig) sig;
        Sort sort = getSort(primSig);
        if (sort == null) {
            // they've passed in something we can't deal with
            return null;
        }
        int sigScope = scoper.sig2scope(sig);

        List<Sig.PrimSig> siblings = allSigs.stream()
                .filter(otherSig -> otherSig instanceof Sig.PrimSig && scoper.isExact(otherSig))
                .map(otherSig -> (Sig.PrimSig) otherSig)
                .filter(otherSig -> primSig.isTopLevel()
                            ? otherSig.isTopLevel() && sort == getSort(otherSig)
                            : primSig.parent == otherSig.parent)
                .sorted(Comparator.comparing(s -> s.label)) // hopefully the labels are unique
                .collect(Collectors.toList());

        // start in the parent's range, then find our offset according to our order with our siblings
        int domainElementStart = primSig.isTopLevel() ? 1 : getDomainElementRange(primSig.parent, scoper).a;
        for (Sig.PrimSig sibling : siblings) {
            if (sibling == sig) {
                break;
            }
            domainElementStart += scoper.sig2scope(sibling);
        }

        return new Pair<>(domainElementStart, domainElementStart + sigScope - 1);
    }

    /**
     * For each position i in the arity of `expr` (i.e. 1<=i<=arity), find the single sort Si such that
     * (x1,...,xn) \in expr implies xi \in Si, or null if no such sort exists.
     * Null corresponds to INDEFINITE in the paper.
     * Returns null for the whole list if the sorts are incompatible.
     */
    public final List<Sort> getMinimalExprSorts(Expr expr, TranslationContext context) {
        try {
            return expr.accept(new SortVisitor(context));
        } catch (SortVisitor.IncompatibleSortsException e) {
            return null;
        }
    }

    /** Convenience overload: throw with errorMessage if the sorts are incompatible. */
    public final List<Sort> getMinimalExprSorts(Expr expr, String errorMessage, TranslationContext context) {
        List<Sort> result = getMinimalExprSorts(expr, context);
        if (result == null) {
            throw new ErrorFatal(errorMessage);
        }
        return result;
    }

    private final class SortVisitor extends FortressVisitReturn<List<Sort>> {

        // Thrown on failure, because exceptions-as-flow-control is the most convenient here (unfortunately)
        private final class IncompatibleSortsException extends RuntimeException {}

        // A copy of the context so we can keep track of which variables have which sorts
        private final TranslationContext context;

        public SortVisitor(TranslationContext context) {
            this.context = new TranslationContext(context);
        }

        private List<Sort> merge(List<Sort> a, List<Sort> b, BiFunction<Sort, Sort, Sort> merger) {
            if (a.size() != b.size()) {
                throw new IncompatibleSortsException();
            }
            List<Sort> merged = new ArrayList<>();
            for (int i = 0; i < a.size(); i++) {
                merged.add(merger.apply(a.get(i), b.get(i)));
            }
            return merged;
        }

        private List<Sort> intersect(List<Sort> a, List<Sort> b) {
            return merge(a, b, this::intersect);
        }

        private List<Sort> union(List<Sort> a, List<Sort> b) {
            return merge(a, b, this::union);
        }

        private Sort intersect(Sort a, Sort b) {
            // If one is null, take the most restrictive option
            if (a == null) {
                return b;
            } else if (b == null) {
                return a;
            } else if (!a.equals(b)) {
                // Incompatible sorts, can't merge!
                throw new IncompatibleSortsException();
            } else {
                // They're the same, pick one
                return a;
            }
        }

        private Sort union(Sort a, Sort b) {
            if (a == null || b == null) {
                return null;
            } else if (!a.equals(b)) {
                // Incompatible sorts!
                throw new IncompatibleSortsException();
            } else {
                // They're the same
                return a;
            }
        }

        @Override
        public List<Sort> visit(ExprBinary x) throws Err {
            // rely on typechecking: e.g. integer ops are always integers, boolean ops are always boolean
            // we don't have to look at their arguments because typechecking checked already
            switch (x.op) {
                case EQUALS:
                case NOT_EQUALS:
                case IN:
                case NOT_IN:
                case IMPLIES:
                case IFF:
                case AND:
                case OR:
                case LT:
                case LTE:
                case GT:
                case GTE:
                case NOT_LT:
                case NOT_LTE:
                case NOT_GT:
                case NOT_GTE:
                    return Collections.singletonList(Sort.Bool());
                case IPLUS:
                case IMINUS:
                case MUL:
                case DIV:
                case REM:
                case SHL:
                case SHR:
                case SHA:
                    return Collections.singletonList(Sort.Int());
            }
            List<Sort> left = visitThis(x.left);
            List<Sort> right = visitThis(x.right);
            List<Sort> result = new ArrayList<>();
            if (x.op.isArrow) {
                // stack the sorts left to right
                result.addAll(left);
                result.addAll(right);
                return result;
            }
            switch (x.op) {
                case JOIN:
                    result.addAll(left.subList(0, left.size() - 1));
                    result.addAll(right.subList(1, right.size()));
                    return result;
                case DOMAIN:
                    if (left.size() != 1) {
                        throw new ErrorFatal("Domain restriction left argument must have arity 1");
                    }
                    result.add(intersect(left.get(0), right.get(0)));
                    result.addAll(right.subList(1, right.size()));
                    return result;
                case RANGE:
                    if (right.size() != 1) {
                        throw new ErrorFatal("Domain restriction left argument must have arity 1");
                    }
                    result.addAll(left.subList(0, left.size() - 1));
                    result.add(intersect(left.get(left.size() - 1), right.get(0)));
                    return result;
                case PLUS:
                case PLUSPLUS: // override
                    return union(left, right);
                case INTERSECT:
                    return intersect(left, right);
                case MINUS:
                    // e1 - e2 has sorts of e1, even if e2's are incompatible, due to short-circuiting
                    return left;
                default:
                    throw new ErrorFatal("Unsupported ExprBinary node: " + x.op);
            }
        }

        @Override
        public List<Sort> visit(ExprList x) throws Err {
            // all possible operations return bool
            return Collections.singletonList(Sort.Bool());
        }

        @Override
        public List<Sort> visit(ExprCall x) throws Err {
            context.addLetMappingsFromCall(x);
            try {
                return visitThis(x.fun.getBody());
            } finally {
                // remove the let mappings even if there's an exception
                context.removeLetMappingsFromCall(x);
            }
        }

        @Override
        public List<Sort> visit(ExprConstant x) throws Err {
            switch (x.op) {
                case TRUE:
                case FALSE:
                    return Collections.singletonList(Sort.Bool());
                case NUMBER:
                case MIN:
                case MAX:
                    return Collections.singletonList(Sort.Int());
                case NEXT:
                    // function int->int
                    return Arrays.asList(Sort.Int(), Sort.Int());
                case IDEN:
                    // We can't assign a single type to iden
                    return Arrays.asList(null, null);
                case EMPTYNESS:
                    // Technically I guess we could assign any type to none, but it seems unsafe
                    return Collections.singletonList(null);
                default:
                    throw new ErrorFatal("Can't get sort from constant: " + x);
            }
        }

        @Override
        public List<Sort> visit(ExprITE x) throws Err {
            return union(visitThis(x.left), visitThis(x.right));
        }

        @Override
        public List<Sort> visit(ExprLet x) throws Err {
            context.addLetMapping(x.var.label, x.expr);
            try {
                return visitThis(x.sub);
            } finally {
                // remove it even if there's an exception
                context.removeMapping(x.var.label);
            }
        }

        @Override
        public List<Sort> visit(ExprQt x) throws Err {
            // trust typechecking
            if (x.op == ExprQt.Op.SUM) {
                return Collections.singletonList(Sort.Int());
            } else if (x.op == ExprQt.Op.COMPREHENSION) {
                // use the sorts from each declaration
                List<Sort> result = new ArrayList<>();
                for (Decl decl : x.decls) {
                    List<Sort> declResult = visitThis(decl.expr);
                    for (ExprHasName ignored : decl.names) {
                        result.addAll(declResult);
                    }
                }
                return result;
            } else {
                // every other op is a formula (all, no, some, etc)
                return Collections.singletonList(Sort.Bool());
            }
        }

        @Override
        public List<Sort> visit(ExprUnary x) throws Err {
            switch (x.op) {
                case SOMEOF:
                case LONEOF:
                case ONEOF:
                case SETOF:
                case EXACTLYOF:
                case CLOSURE:
                case RCLOSURE:
                case NOOP:
                case CAST2INT: // these might be int-typed, but we ignore them in the translation
                case CAST2SIGINT: // so let's ignore them here too
                    return visitThis(x.sub);
                case NOT:
                case NO:
                case SOME:
                case LONE:
                case ONE:
                    return Collections.singletonList(Sort.Bool());
                case CARDINALITY:
                    return Collections.singletonList(Sort.Int());
                case TRANSPOSE: {
                    // swap them around
                    List<Sort> sub = visitThis(x.sub);
                    if (sub.size() != 2) {
                        throw new ErrorFatal("Transpose argument must have arity 2!");
                    }
                    return Arrays.asList(sub.get(1), sub.get(0));
                }
                default:
                    throw new ErrorFatal("Unsupported ExprUnary node: " + x.op);
            }
        }

        @Override
        public List<Sort> visit(ExprVar x) throws Err {
            // use the sort it's mapped to in the context
            if (context.hasLetMapping(x.label)) {
                TranslationContext.LetContext mapping = context.getLetMapping(x.label);
                assert mapping != null;
                mapping.useLetMapping(context);
                try {
                    return visitThis(mapping.getExpr());
                } finally {
                    mapping.resetMapping(); // reset even in case of exception
                }
            } else if (context.hasVarMapping(x.label)) {
                AnnotatedVar mapped = context.getVarMapping(x.label);
                assert mapped != null;
                return Collections.singletonList(mapped.sort());
            } else {
                // try to get the sort from the type
                return getTypeSorts(x.type());
            }
        }

        @Override
        public List<Sort> visit(ExprElementOf x) throws Err {
            return Collections.singletonList(Sort.Bool());
        }

        @Override
        public List<Sort> visit(Sig x) throws Err {
            // fetch it using our policy
            return Collections.singletonList(getSort(x));
        }

        @Override
        public List<Sort> visit(Sig.Field x) throws Err {
            // manually construct the sort for S->e for the translation of "sig S { f: e }"
            List<Sort> sigSorts = visitThis(x.sig);
            List<Sort> exprSorts = visitThis(x.decl().expr);
            List<Sort> result = new ArrayList<>(sigSorts);
            result.addAll(exprSorts);
            return result;
        }

        @Override
        public List<Sort> visit(Func x) throws Err {
            throw new ErrorFatal("Visiting Func isn't supported!");
        }

        @Override
        public List<Sort> visit(Assert x) throws Err {
            throw new ErrorFatal("Visiting Assert isn't supported!");
        }

        @Override
        public List<Sort> visit(Macro macro) throws Err {
            throw new ErrorFatal("Visiting Macro isn't supported!");
        }
    }

    /**
     * Given an Alloy type, assert that all its product types have arity > idx and that all the product types have the
     * same sort in the idx'th position, then return that common sort.
     */
    public final Sort getIndexSort(int idx, Type type) {
        return checkAllEqual(StreamSupport.stream(type.spliterator(), false)
                .map(productType -> productType.get(idx))
                .map(this::getSort)
                .collect(Collectors.toList()),
                "Product types of '" + type + "' do not have same sort at index: " + idx);
    }

    /** Check that all the exprs are formulas, and throw an error if not */
    public final void checkIsFormula(String err, Iterable<? extends Expr> exprs) {
        boolean allFormulas = StreamSupport.stream(exprs.spliterator(), false)
                .allMatch(expr -> expr.type().is_bool);
        if (!allFormulas) {
            throw new ErrorFatal(err);
        }
    }

    /** Convenience overload of the above. */
    public final void checkIsFormula(String err, Expr... exprs) {
        checkIsFormula(err, Arrays.asList(exprs));
    }

    /** Check that all the exprs are unary int expressions, and throw an error if not. */
    public final void checkIsInt(String err, Iterable<? extends Expr> exprs) {
        List<Sort> commonSorts = checkSameSort(err, exprs);
        if (commonSorts.size() != 1 || !Sort.Int().equals(commonSorts.get(0))) {
            throw new ErrorFatal(err);
        }
    }

    public final void checkIsInt(String err, Expr... exprs) {
        checkIsInt(err, Arrays.asList(exprs));
    }

    /**
     * Given an Alloy type, assert that it has only one arity and that all the product types in each position have
     * the same sorts, then return a list of the common sorts.
     */
    public final List<Sort> getTypeSorts(Type type) {
        int arity = type.arity();
        if (arity == -1) {
            throw new ErrorFatal("Portus does not support sets with multiple arities!");
        }
        return IntStream.range(0, arity)
                .mapToObj(idx -> getIndexSort(idx, type))
                .collect(Collectors.toList());
    }

    /** Assert that all the exprs have the same sorts at each position in their type, and return the common sorts. */
    public final List<Sort> checkSameSort(String err, Iterable<? extends Expr> exprs) {
        List<List<Sort>> sortLists = StreamSupport.stream(exprs.spliterator(), false)
                .map(expr -> getTypeSorts(expr.type()))
                .collect(Collectors.toList());
        int arity = checkAllEqual(sortLists.stream().map(List::size).collect(Collectors.toList()), err);
        // check that all the sorts are equal at each position
        return IntStream.range(0, arity)
                .mapToObj(idx -> checkAllEqual(sortLists.stream()
                        .map(sortList -> sortList.get(idx))
                        .collect(Collectors.toList()), err))
                .collect(Collectors.toList());
    }

    private <T> T checkAllEqual(Iterable<? extends T> items, String message) {
        T common = null;
        for (T item : items) {
            if (common == null) {
                common = item;
            } else if (!common.equals(item)) {
                throw new ErrorFatal(message);
            }
        }
        return common;
    }

}
