package ca.uwaterloo.watform.portus;

import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.ErrorFatal;
import edu.mit.csail.sdg.ast.Assert;
import edu.mit.csail.sdg.ast.Decl;
import edu.mit.csail.sdg.ast.Expr;
import edu.mit.csail.sdg.ast.ExprBinary;
import edu.mit.csail.sdg.ast.ExprCall;
import edu.mit.csail.sdg.ast.ExprConstant;
import edu.mit.csail.sdg.ast.ExprHasName;
import edu.mit.csail.sdg.ast.ExprITE;
import edu.mit.csail.sdg.ast.ExprLet;
import edu.mit.csail.sdg.ast.ExprList;
import edu.mit.csail.sdg.ast.ExprQt;
import edu.mit.csail.sdg.ast.ExprUnary;
import edu.mit.csail.sdg.ast.ExprVar;
import edu.mit.csail.sdg.ast.Func;
import edu.mit.csail.sdg.ast.Sig;
import edu.mit.csail.sdg.ast.Type;
import edu.mit.csail.sdg.parser.Macro;
import edu.mit.csail.sdg.translator.ScopeComputer;
import fortress.modelfind.ModelFinder;
import fortress.msfol.Sort;
import fortress.msfol.Theory;
import fortress.problemstate.ExactScope;
import fortress.problemstate.NonExactScope;
import fortress.problemstate.Scope;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.StreamSupport;

/**
 * An abstraction responsible for assigning sigs to sorts. Should be immutable.
 */
// TODO: It's probably possible to remove most of the type-based sort determining
public abstract class SortPolicy {

    protected final List<Sig> allSigs;

    public SortPolicy(Iterable<Sig> allSigs) {
        // For now: filter out Sig.STRING since we don't support strings
        // TODO: Support strings
        this.allSigs = PortusUtil.iterableToList(allSigs).stream()
                .filter(sig -> sig != Sig.STRING)
                .collect(Collectors.toList());
    }

    /**
     * Get the sort assigned to a given signature. Should have no side effects.
     * May return null for sigs that cannot be assigned a sort (e.g. univ, none) since they encompass all sorts.
     */
    public abstract Sort getSort(Sig sig);

    /**
     * Get the scope of the given sort. Assert that it was one generated by the sort policy.
     * Note that the scope of Int is the number of integers (i.e., 2^bitwidth, not the bitwidth itself).
     */
    public abstract int getSortScope(Sort sort);

    /**
     * Is every atom in sig's sort a member of sig?
     */
    public abstract boolean isSigEntireSort(Sig sig);

    /** Return a theory with the sorts assigned by the policy added. */
    public abstract Theory addSortsToTheory(Theory theory);

    /**
     * Add all the scopes of the sorts to the model finder.
     * {@code unchangingSorts} is the list of sorts which should be marked as 'unchanging': their scope cannot be
     * changed in the output (without messing up the semantics of the problem).
     */
    public void configureModelFinderScopes(ModelFinder modelFinder, Set<Sort> forcedExactScopeSorts,
                                           Set<Sort> unchangingSorts, ScopeComputer scoper) {
        for (Map.Entry<Sort, Scope> sortAndScope : getSortToScopeMap(
                forcedExactScopeSorts, unchangingSorts, scoper).entrySet()) {
            modelFinder.setScope(sortAndScope.getKey(), sortAndScope.getValue());
        }
    }

    /** Get the list of all sorts that may be assigned by the policy. */
    public abstract List<Sort> getAllSorts();

    /** Reverse-engineer a primitive sig from a sort returned by getSort. */
    protected Sig.PrimSig getAnySigFromSort(Sort sort) {
        // Note that every sort should have at least one PrimSig (can't be only subset sigs).
        // This has time complexity O(scary), but should be fine since there's not that many sigs.
        for (Sig sig : allSigs) {
            if (sig instanceof Sig.PrimSig && Objects.equals(getSort(sig), sort)) {
                return (Sig.PrimSig) sig;
            }
        }
        return null;
    }

    /**
     * Get a map of sorts assigned by the policy to their Fortress scopes.
     * This method is for configuring model finders and dumping. Use getSortScope() for most use-cases.
     */
    public Map<Sort, Scope> getSortToScopeMap(
            Set<Sort> forcedExactScopeSorts, Set<Sort> unchangingSorts, ScopeComputer scoper) {
        return getAllSorts().stream().collect(Collectors.toMap(sort -> sort, sort -> {
            int scope = getSortScope(sort);
            boolean isForcedExact = forcedExactScopeSorts.contains(sort);
            boolean isUnchanging = unchangingSorts.contains(sort);

            boolean isExact;
            if (isForcedExact) {
                // We're forced to make the scope exact: a membership predicate is used
                isExact = true;
            } else {
                Sig.PrimSig anySig = getAnySigFromSort(sort);
                if (isSigEntireSort(anySig)) {
                    // There's only one sig in the sort: use exact or non exact depending on sig's scope's exactness
                    isExact = scoper.isExact(anySig);
                } else {
                    // There are multiple sigs in the scope: Portus handles scope and exactness
                    isExact = true;
                }
            }

            if (isExact) {
                return ExactScope.apply(scope, isUnchanging);
            } else {
                return NonExactScope.apply(scope, isUnchanging);
            }
        }));
    }

    /**
     * Statically find the sort resolvant that describes the possible Fortress sorts that expr could have.
     * @see SortResolvant
     */
    public final SortResolvant getMinimalExprSorts(Expr expr, VarMappingContext varMappingContext) {
        return expr.accept(new SortVisitor(varMappingContext));
    }

    public final SortResolvant getMinimalExprSorts(Expr expr, TranslationContext context) {
        return getMinimalExprSorts(expr, context.varMappingContext);
    }

    /**
     * For convenience, throw an error if any of the sort resolvants aren't definite,
     * and return the definite sorts.
     */
    public static List<Sort> requireAllSortsDefinite(SortResolvant sortResolvant, String errorMessage) {
        if (!sortResolvant.isDefinite()) {
            // We can throw ErrorNoPortusSupport because Kodkod doesn't have any notion of definite sorts,
            // so this function *should* disallow only models that Kodkod allows.
            throw new ErrorNoPortusSupport(errorMessage);
        }
        return sortResolvant.getDefiniteSorts();
    }

    public final List<Sort> getMinimalExprDefiniteSorts(
            Expr expr, String errorMessage, VarMappingContext varMappingContext) {
        return requireAllSortsDefinite(getMinimalExprSorts(expr, varMappingContext), errorMessage);
    }

    public final List<Sort> getMinimalExprDefiniteSorts(Expr expr, String errorMessage, TranslationContext context) {
        return getMinimalExprDefiniteSorts(expr, errorMessage, context.varMappingContext);
    }

    private class SortVisitor extends ContextVisitReturn<SortResolvant> {

        public SortVisitor(VarMappingContext context) {
            super(context, SortPolicy.this);
        }

        @Override
        public SortResolvant visit(ExprBinary x) throws Err {
            // rely on typechecking: e.g. integer ops are always integers, boolean ops are always boolean
            // we don't have to look at their arguments because typechecking checked already
            switch (x.op) {
                case EQUALS:
                case NOT_EQUALS:
                case IN:
                case NOT_IN:
                case IMPLIES:
                case IFF:
                case AND:
                case OR:
                case LT:
                case LTE:
                case GT:
                case GTE:
                case NOT_LT:
                case NOT_LTE:
                case NOT_GT:
                case NOT_GTE:
                    return SortResolvant.definite(Sort.Bool());
                case IPLUS:
                case IMINUS:
                case MUL:
                case DIV:
                case REM:
                case SHL:
                case SHR:
                case SHA:
                    return SortResolvant.definite(Sort.Int());
            }
            SortResolvant left = visitThis(x.left);
            SortResolvant right = visitThis(x.right);
            if (x.op.isArrow) {
                return left.cartesianProduct(right);
            }
            switch (x.op) {
                case JOIN:
                    return left.join(right);
                case DOMAIN:
                    if (left.arity() != 1) {
                        throw new ErrorFatal("Domain restriction left argument must have arity 1");
                    }
                    // restrict to only tuples with leftmost sort `left`, then add `left` back
                    return left.cartesianProduct(left.join(right));
                case RANGE:
                    if (right.arity() != 1) {
                        throw new ErrorFatal("Range restriction right argument must have arity 1");
                    }
                    // restrict to only tuples with rightmost sort `right`, then add `right` back
                    return left.join(right).cartesianProduct(right);
                case PLUS:
                case PLUSPLUS: // override
                    return left.union(right);
                case INTERSECT:
                    return left.intersection(right);
                case MINUS:
                    // e1 - e2 has sorts of e1, even if e2's are incompatible, due to short-circuiting
                    return left;
                default:
                    throw new ErrorFatal("Unsupported ExprBinary node: " + x.op);
            }
        }

        @Override
        public SortResolvant visit(ExprList x) throws Err {
            // all possible operations return bool
            return SortResolvant.definite(Sort.Bool());
        }

        @Override
        public SortResolvant visit(ExprCall x) throws Err {
            varMappingContext.addLetMappingsFromCall(x);
            try {
                return visitThis(x.fun.getBody());
            } finally {
                // remove the let mappings even if there's an exception
                varMappingContext.removeLetMappingsFromCall(x);
            }
        }

        @Override
        public SortResolvant visit(ExprConstant x) throws Err {
            switch (x.op) {
                case TRUE:
                case FALSE:
                    return SortResolvant.definite(Sort.Bool());
                case NUMBER:
                case MIN:
                case MAX:
                    return SortResolvant.definite(Sort.Int());
                case NEXT:
                    // function int->int
                    return SortResolvant.definite(Sort.Int(), Sort.Int());
                case IDEN:
                    return SortResolvant.iden(SortPolicy.this);
                case EMPTYNESS:
                    return SortResolvant.NONE;
                default:
                    throw new ErrorNoPortusSupport("Can't get sort from constant: " + x);
            }
        }

        @Override
        public SortResolvant visit(ExprITE x) throws Err {
            return visitThis(x.left).union(visitThis(x.right));
        }

        @Override
        public SortResolvant visitLet(ExprLet x) throws Err {
            return visitThis(x.sub); // let mappings handled by superclass
        }

        @Override
        public SortResolvant visitQuantifier(ExprQt x, List<SortResolvant> ignoredArgResults) throws Err {
            // trust typechecking
            if (x.op == ExprQt.Op.SUM) {
                return SortResolvant.definite(Sort.Int());
            } else if (x.op == ExprQt.Op.COMPREHENSION) {
                // use the sorts from each declaration
                SortResolvant result = null;
                for (Decl decl : x.decls) {
                    SortResolvant declResult = visitThis(decl.expr);
                    for (ExprHasName ignored : decl.names) {
                        if (result == null) {
                            result = declResult;
                        } else {
                            result = result.cartesianProduct(declResult);
                        }
                    }
                }
                return result;
            } else {
                // every other op is a formula (all, no, some, etc)
                return SortResolvant.definite(Sort.Bool());
            }
        }

        @Override
        public SortResolvant visit(ExprUnary x) throws Err {
            switch (x.op) {
                case SOMEOF:
                case LONEOF:
                case ONEOF:
                case SETOF:
                case EXACTLYOF:
                case CLOSURE: // assume it's well-typed: arity 2 and subset of iden
                case NOOP:
                case CAST2INT: // these might be int-typed, but we ignore them in the translation
                case CAST2SIGINT: // so let's ignore them here too
                    return visitThis(x.sub);
                case NOT:
                case NO:
                case SOME:
                case LONE:
                case ONE:
                    return SortResolvant.definite(Sort.Bool());
                case CARDINALITY:
                    return SortResolvant.definite(Sort.Int());
                case TRANSPOSE: {
                    // swap them around
                    SortResolvant sub = visitThis(x.sub);
                    if (sub.arity() != 2) {
                        throw new ErrorFatal("Transpose argument must have arity 2!");
                    }
                    return sub.transpose();
                }
                case RCLOSURE:
                    // rclosure = closure + iden
                    return visitThis(x.sub).union(SortResolvant.iden(SortPolicy.this));
                default:
                    throw new ErrorFatal("Unsupported ExprUnary node: " + x.op);
            }
        }

        @Override
        public SortResolvant visitVar(ExprVar x) throws Err {
            // use the sort it's mapped to in the context
            // Note: let mappings are automatically expanded in superclass
            if (varMappingContext.hasTermMapping(x.label)) {
                AnnotatedTerm mapped = varMappingContext.getTermMapping(x.label);
                assert mapped != null;
                return SortResolvant.definite(mapped.getSort());
            } else {
                // unknown variable
                // try to get the sort from the type - TODO this probably isn't necessary (except for tests)
                return SortResolvant.definite(getTypeSorts(x.type()));
            }
        }

        @Override
        public SortResolvant visit(ExprElementOf x) throws Err {
            return SortResolvant.definite(Sort.Bool());
        }

        @Override
        public SortResolvant visit(Sig x) throws Err {
            if (x.equals(Sig.UNIV)) {
                return SortResolvant.univ(SortPolicy.this);
            } else if (x.equals(Sig.NONE)) {
                return SortResolvant.NONE;
            } else if (x.equals(Sig.STRING)) {
                throw new ErrorNoPortusSupport("Portus does not support strings!");
            }

            // fetch it using our policy
            return SortResolvant.definite(getSort(x));
        }

        @Override
        public SortResolvant visit(Sig.Field x) throws Err {
            // manually construct the sort for S->e for the translation of "sig S { f: e }"
            SortResolvant sigSorts = visitThis(x.sig);

            // map "this" in order to visit the field's expr, since it might be defined relatively
            // we map "this" to the sig because it has the right sort
            varMappingContext.addLetMapping("this", x.sig);
            SortResolvant exprSorts;
            try {
                exprSorts = visitThis(x.decl().expr);
            } finally {
                varMappingContext.removeMapping("this");
            }

            return sigSorts.cartesianProduct(exprSorts);
        }

        @Override
        public SortResolvant visit(Func x) throws Err {
            throw new ErrorFatal("Visiting Func isn't supported!");
        }

        @Override
        public SortResolvant visit(Assert x) throws Err {
            throw new ErrorFatal("Visiting Assert isn't supported!");
        }

        @Override
        public SortResolvant visit(Macro macro) throws Err {
            throw new ErrorFatal("Visiting Macro isn't supported!");
        }
    }

    /**
     * Given an Alloy type, assert that all its product types have arity > idx and that all the product types have the
     * same sort in the idx'th position, then return that common sort.
     */
    public final Sort getIndexSort(int idx, Type type) {
        return checkAllEqual(StreamSupport.stream(type.spliterator(), false)
                .map(productType -> productType.get(idx))
                .map(this::getSort)
                .collect(Collectors.toList()),
                "Product types of '" + type + "' do not have same sort at index: " + idx);
    }

    /** Check that all the exprs are formulas, and throw an error if not */
    public final void checkIsFormula(String err, Iterable<? extends Expr> exprs) {
        boolean allFormulas = StreamSupport.stream(exprs.spliterator(), false)
                .allMatch(expr -> expr.type().is_bool);
        if (!allFormulas) {
            throw new ErrorFatal(err);
        }
    }

    /** Convenience overload of the above. */
    public final void checkIsFormula(String err, Expr... exprs) {
        checkIsFormula(err, Arrays.asList(exprs));
    }

    /** Check that all the exprs are unary int expressions, and throw an error if not. */
    public final void checkIsInt(String err, Iterable<? extends Expr> exprs) {
        List<Sort> commonSorts = checkSameSort(err, exprs);
        if (commonSorts.size() != 1 || !Sort.Int().equals(commonSorts.get(0))) {
            throw new ErrorFatal(err);
        }
    }

    public final void checkIsInt(String err, Expr... exprs) {
        checkIsInt(err, Arrays.asList(exprs));
    }

    /**
     * Given an Alloy type, assert that it has only one arity and that all the product types in each position have
     * the same sorts, then return a list of the common sorts.
     */
    public final List<Sort> getTypeSorts(Type type) {
        int arity = type.arity();
        if (arity == -1) {
            throw new ErrorNoPortusSupport("Portus does not support sets with multiple arities!");
        }
        return IntStream.range(0, arity)
                .mapToObj(idx -> getIndexSort(idx, type))
                .collect(Collectors.toList());
    }

    /** Assert that all the exprs have the same sorts at each position in their type, and return the common sorts. */
    public final List<Sort> checkSameSort(String err, Iterable<? extends Expr> exprs) {
        List<List<Sort>> sortLists = StreamSupport.stream(exprs.spliterator(), false)
                .map(expr -> getTypeSorts(expr.type()))
                .collect(Collectors.toList());
        int arity = checkAllEqual(sortLists.stream().map(List::size).collect(Collectors.toList()), err);
        // check that all the sorts are equal at each position
        return IntStream.range(0, arity)
                .mapToObj(idx -> checkAllEqual(sortLists.stream()
                        .map(sortList -> sortList.get(idx))
                        .collect(Collectors.toList()), err))
                .collect(Collectors.toList());
    }

    private <T> T checkAllEqual(Iterable<? extends T> items, String message) {
        T common = null;
        for (T item : items) {
            if (common == null) {
                common = item;
            } else if (!common.equals(item)) {
                throw new ErrorFatal(message);
            }
        }
        return common;
    }

}
